Feature/tda 83
meaningfy-ws/ted-data-eu pull request #27
Opened 2023-02-21 14:41 UTC by duprijil

2023-02-21 14:45 UTC, kaleanych approved these changes
Looks ok. Check the comments

2023-02-21 14:45 UTC, kaleanych commented on ted_data_eu/adapters/storage.py
> +        self.host = host if host else config.ELASTIC_HOST
self.host = host or config.ELASTIC_HOST

Also for similar inline ifs

it is more compact

2023-02-21 18:38 UTC, CaptainOfHacks commented on ted_data_eu/__init__.py
> +ELASTIC_SUBDOMAIN = 'elastic'
remove this from constants

2023-02-21 18:39 UTC, CaptainOfHacks commented on ted_data_eu/__init__.py
> +        return f"https://{ELASTIC_SUBDOMAIN}.{self.DOMAIN}"
ELASTIC_HOST need to be a full URL in .env and register in Vault,

2023-02-21 18:39 UTC, CaptainOfHacks commented on ted_data_eu/__init__.py
> +    def DOMAIN(self, config_value: str) -> str:
remove this secret, is used somewhere?

2023-02-21 18:41 UTC, CaptainOfHacks commented on ted_data_eu/adapters/storage.py
> +    def add_document(self, document: str) -> Response:
document will be string? or JSON string, if JSON string I recommand to use dict object and convert to JSON string inside adapter.

2023-02-21 18:43 UTC, CaptainOfHacks commented on ted_data_eu/adapters/storage.py
> +    def add_document(self, document: str) -> Response:
Result, as Response is very dependent by Elastic behaviour, I recommend checking response and raise exception if something went wrong.

2023-02-21 18:43 UTC, CaptainOfHacks commented on ted_data_eu/adapters/storage.py
> +        return response
Result, as Response is very dependent by Elastic behaviour, I recommend checking response and raise exception if something went wrong.

2023-02-21 18:44 UTC, CaptainOfHacks commented on ted_data_eu/adapters/storage.py
> +                 index: str,
I recommend renaming index, in elastic_index

2023-02-21 18:51 UTC, CaptainOfHacks commented on ted_data_eu/adapters/storage.py
> +    def query(self, query: str) -> Response:
Result, as Response is very dependent by Elastic behaviour, I recommend checking response and raise exception if something went wrong.

2023-02-21 18:52 UTC, CaptainOfHacks commented on ted_data_eu/services/data_load_service.py
> +ELASTIC_DEFAULT_INDEX = 'ted_data'
add this variable in config

2023-02-21 19:02 UTC, CaptainOfHacks commented on tests/e2e/test_document_storage.py
> +        assert item['create']['status'] == 201
I recommend to implement Exception mechanism when something went wrong, and create custom Exceptions for Elastic HTTP API exceptions.

2023-02-21 19:03 UTC, CaptainOfHacks requested changes
Great implementation! Just some adjustments need to do.

2023-02-22 15:16 UTC, CaptainOfHacks commented on ted_data_eu/adapters/storage.py
> +            raise Exception(
Create custom exception, is difficult to catch general Exception, create ElasticStorageExaption class.

2023-02-22 15:18 UTC, CaptainOfHacks commented on ted_data_eu/services/data_load_service.py
> +    if not storage:
replace not storage to storage is None

2023-02-22 15:21 UTC, CaptainOfHacks commented on ted_data_eu/adapters/storage.py
> +    def add_documents(self, documents: List[Dict]) -> Dict:
This method should return nothing, when we return JSON response we create a dependency where we call this function.

2023-02-22 15:24 UTC, CaptainOfHacks commented on tests/e2e/test_document_storage.py
> +    assert result['errors'] is False
If we correctly decoupling, this type of verification should be removed.

2023-02-22 15:25 UTC, CaptainOfHacks commented on tests/e2e/test_document_storage.py
> +    for item in result['items']:
Here I see, we need a Storage method to inspect an index, how many documents are in a specific index or get list of documents.

2023-02-22 15:26 UTC, CaptainOfHacks commented on tests/e2e/test_document_storage.py
> +        assert item['create']['status'] == 201
After we insert documents in storage, we can check with a get function.

2023-02-22 15:27 UTC, CaptainOfHacks commented on tests/e2e/test_document_storage.py
> +        assert item['create']['status'] == 201
Here I see an unknown for service layer response structure. We need to remove this response and use only raise Exception mechanism when something went wrong.

2023-02-22 15:28 UTC, CaptainOfHacks commented on tests/e2e/test_document_storage.py
> +    response = elastic_storage.add_document(test_doc)
Here I see an unknown for service layer response structure. We need to remove this response and use only raise Exception mechanism when something went wrong.

2023-02-22 15:28 UTC, CaptainOfHacks commented on tests/e2e/test_document_storage.py
> +    response = elastic_storage.clear()
Here I see an unknown for service layer response structure. We need to remove this response and use only raise Exception mechanism when something went wrong.

2023-02-22 15:30 UTC, CaptainOfHacks commented on tests/e2e/test_document_storage.py
> +    assert response['_shards']['successful'] > 0
for QueryResult we need a concrete ObjectType, this general dictionary response introduce an ElasticSearch direct dependency ( and a unknown dictionary structure ).

2023-02-22 15:39 UTC, CaptainOfHacks requested changes
Just a few little adjustments need to do.
The scope of an adapter is to full decoupling the internal system logic and external system's logic.
The scope of a service is to resolve/realize a concrete need (this need use only internal services, adapters, without external dependencies as logic, behaviour, errors, data structures, HTTP REST API response structure, or any uncontrolled in our system resources).

2023-03-01 20:50 UTC, CaptainOfHacks approved these changes

2023-03-01 20:51 UTC, merged